### ISSUE TITLE
Sass 入门基础

### ISSUE THREAD

**Issue by pinggod** [pinggod/blog-archive#4]
# Sass 入门基础

我有一个梦想，再也不用编写重复的代码。

CSS 是一门声明式语言，基本上没有逻辑结构可言。Sass 等预处理器最大的优势，就在于为 CSS 添加了逻辑结构和其他语法糖，让其具有了复用、可读、可扩、可维护等优雅的特性。这也是最吸引我使用它们的原因。

目前，我最喜欢的是 Sass，主要原因是相关资源比较丰富、更新及时、社区活跃。其他预处理器都各有优势，根据个人习惯选用即可。

本文是关于 Sass 的入门基础教程，但不是教你怎么来用 Sass 写嵌套语法的。为什么这么说？因为许多初学者浅尝辄止，了解了 Sass 十分之一的表面就不再愿意进一步深入了，远远达不到及格线。

懒惰在计算机世界是一种美德，前提是你要有偷懒的资本。Sass 的强大可以让你在 CSS 的各个方面都有偷懒的资本。

## 编码

编码声明，应该置于入口文件的第一行，有助于解决字符集相关的各种灵异问题。

```scss
@charset “utf-8”;
```

## 嵌套

Sass 支持在规则集内嵌套其他规则集。

```scss
body {
  width: 97%;
  p, div {
    font-size: 2em;
    a { font-weight: bold; }
  }
  pre { font-size: 3em; }
}
```

生成的 CSS：

```css
body {
  width: 97%;
}
body p, body div {
  font-size: 2em;
}
body p a, body div a {
  font-weight: bold;
}
body pre {
  font-size: 3em;
}
```

## 父级引用符：`&`

父级引用符 `&`，更像是一个默认值为父级选择器的插值符号。

```scss
#main {
  color: black;
  a {
    font-weight: bold;
    &:hover { color: red; }
  }
}
```

生成的 CSS：

```
#main {
  color: black;
}
#main a {
  font-weight: bold;
}
#main a:hover {
  color: red;
}
```

如果父级元素未定义，是否可以提供一些预备措施？当然！

```scss
@mixin does-parent-exist {
  @if & {
    &:hover {
      color: red;
    }
  } @else {
    a {
      color: red;
    }
  }
}

@include does-parent-exist();
```

生成的 CSS：

```css
a { 
  color: red; 
}
```

## 嵌套型属性

对于复合属性，Sass 支持一种嵌套型的写法：

```scss
.funky {
  font: 20px/24px fantasy {
    weight: bold;
  }
}
```

生成的 CSS：

```css
.funky {
  font: 20px/24px fantasy;
  font-weight: bold;
}
```

## 变量
Sass 的强大之处就在于其具有完整的逻辑操作方案。其中最基础的，就是声明和赋值变量：

```scss
$font-size: 2em;

h1 {
    font-size: $font-size;
}
```

>由于历史原因，变量中间的连字符和下划线可以互换，即 `-` 等同于 `_`。

## 数据类型

Sass 包含了七种数据类型：

- 数值
- 字符串
- 颜色值
- 布尔值
- null 类型
- 列表
- 映射（`map`）

### 字符串

Sass 中包含两种字符串：使用引号包裹的字符串和不包裹的字符串，比如 `"Lucida Grande"` 和 `bold`。当使用插值语法（`#{}`）时，被引用的字符串将会自动去除引号。

```scss
@mixin firefox-message($selector) {
  body.firefox #{$selector}:before {
    content: "Hi, Firefox users!";
  }
}

@include firefox-message(".header");
```

生成的 CSS：

```css
body.firefox .header:before {
  content: "Hi, Firefox users!"; 
}
```

## 操作符

每种数据类型都支持等号（`==`）和不等号（`!=`）运算符。

### 数值运算

数值还包括加减乘除以及模运算符。其中，除法运算符比较特殊：

```scss
// Input：SCSS
p {
  font: 10px/8px;             // Plain CSS, no division
  $width: 1000px;
  width: $width/2;            // Uses a variable, does division
  width: round(1.5)/2;        // Uses a function, does division
  height: (500px/2);          // Uses parentheses, does division
  margin-left: 5px + 8px/2px; // Uses +, does division
}
```

生成的 CSS：

```css
p {
  font: 10px/8px;
  width: 500px;
  height: 250px;
  margin-left: 9px; }
```

由于 Sass 中没有转义字符，所以，想要原生输出反斜线，可以使用插值语法：

```scss
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```

生成的 CSS：

```css
p {
  font: 12px/30px; 
}
```

### 颜色值运算符

是的，颜色值可以进行运算！对于 `rgba` 和 `hsla` 颜色值，必须保证透明度相同才能进行运算。

```scss
p {
  color: rgba(255, 0, 0, 0.75) + rgba(0, 255, 0, 0.75);
}
```

生成的 CSS：

```css
p {
  color: rgba(255, 255, 0, 0.75); 
}
```

可以通过 `opacify` 和 `transparentize` 函数调节透明度：

```scss
$translucent-red: rgba(255, 0, 0, 0.5);
p {
  color: opacify($translucent-red, 0.3);
  background-color: transparentize($translucent-red, 0.25);
}
```

生成的 CSS：

```css
p {
  color: rgba(255, 0, 0, 0.8);
  background-color: rgba(255, 0, 0, 0.25); 
}
```

### 字符串操作符

字符串的加法操作是个很神奇的运算：当第一个运算子被引号包裹时，那么结果就会被引号包裹；如果第一个预算子未被包裹，那么结果也不会被引号包裹。

```scss
p:before {
  content: "Foo " + Bar;
  font-family: sans- + "serif";
}
```

生成的 CSS：

```css
p:before {
  content: "Foo Bar";
  font-family: sans-serif; }
```

另外一个神奇的特性是在字符串中使用插值语句，实现动态赋值：

```scss
p:before {
  content: "I ate #{5 + 10} pies!";
}
```

生成的 CSS：

```css
p:before {
  content: "I ate 15 pies!"; }
```

空的插值：

```
$value: null;
p:before {
  content: "I ate #{$value} pies!";
}
```

生成的 CSS：

```css
p:before {
  content: "I ate  pies!"; }
```

>如果插值内容为 `null` 类型，只会产生一个空字符。

### 布尔操作符

布尔值支持 `and`、`or` 和 `not` 操作符进行布尔值运算。

## 插值 `#{}`

通过使用插值语法，可以实现动态赋值。

```scss
$name: foo;
$attr: border;
p.#{$name} {
  #{$attr}-color: blue;
}
```

生成的 CSS：

```css
p.foo {
  border-color: blue; 
}
```

## 变量标识符

在 Sass 中，可以给变量添加两种标识符：`!default` 和 `!global`。Sass 中的变量不能只声明不定义，至少定义为 `null` 类型，所以，当变量被定义时，就一定会存在一个值。同时，还可以多次定义该变量，在具体的作用域中，根据最近原则使用变量值。

有了上面的基础知识，那么我们就可以来辨析 `!default` 和 `!global` 的差异了。拥有 `!default` 标识符的变量，相当于为变量设置了默认值。如果再次对该变量进行定义，那么将会忽略声明顺序，使用新的值，不再使用默认值。

`!global`，顾名思义，就是设置全局变量。对于声明在所有函数外的变量，无论是否使用该标识符，都可以被其他函数所调用，所以此时，该标识符更像是一种`标志`；对于声明在函数内的变量，使用该标识符之后，即可将其提升为全局变量，为所有的函数所调用。但是从另一种角度来看，是否有必要在函数内声明全局变量，还有待商榷，毕竟这种方式的可维护性和可扩展性太低。

`!default` 标志：

```scss
$content: "First content";
$content: "Second content?" !default;
$new_content: "First time reference" !default;

#main {
  content: $content;
  new-content: $new_content;
}
```

生成的 CSS：

```css
#main {
  content: "First content";
  new-content: "First time reference"; }
```

`!global` 标志：

```scss
#main {
  $width: 5em !global;
  width: $width;
}

#sidebar {
  width: $width;
}
```

生成的 CSS：

```css
#main {
  width: 5em;
}

#sidebar {
  width: 5em;
}
```

有一种情况例外，当变量值为 `null` 时，相当于未定义，所以解析器会再查找最近的定义，找到就是用，没找到就是用默认值。

```scss
$content: null;
$content: "Non-null content" !default;

#main {
  content: $content;
}
```

生成的 CSS：

```css
#main {
  content: "Non-null content"; 
}
```

### `@import`

`@import` 指令可以用于从外部加载文件：

```scss
@import "foo.scss";
// 可以同时加载多个文件
@import "rounded-corners", "text-shadow";
// 可以在 url() 中使用插值
$family: unquote("Droid+Sans");
@import url("http://fonts.googleapis.com/css?family=#{$family}");
```

不建议在嵌套结构中使用 `@import`，尤其是混合宏和其他指令的嵌套结构中。

### `@media`

`@media` 指令和 CSS 基本类似，唯一的不同之处在于，即使该指令的内容写在了嵌套结构中，在变异之后也会被提取到外部：

```scss
.sidebar {
  width: 300px;
  @media screen and (orientation: landscape) {
    width: 500px;
  }
}
```

生成的 CSS：

```css
.sidebar {
  width: 300px;
}
@media screen and (orientation: landscape) {
  .sidebar {
    width: 500px;
  }
}
```

此外，`@media` 指令内可以使用 SassScript 表达式（变量、函数和操作符）：

```scss
$media: screen;
$feature: -webkit-min-device-pixel-ratio;
$value: 1.5;

@media #{$media} and ($feature: $value) {
  .sidebar {
    width: 500px;
  }
}
```

生成的 CSS：

```css
@media screen and (-webkit-min-device-pixel-ratio: 1.5) {
  .sidebar {
    width: 500px;
  }
}
```

### `@extend`

`@extend` 指令可以用来继承其他规则集：

```scss
.error {
  border: 1px #f00;
  background-color: #fdd;
}
.seriousError {
  @extend .error;
  border-width: 3px;
}
```

生成的 CSS：

```
.error, .seriousError {
  border: 1px #f00;
  background-color: #fdd;
}

.seriousError {
  border-width: 3px;
}
```

有时候我们会见到一些匪夷所思的现象：

```scss
.error {
  border: 1px #f00;
  background-color: #fdd;
}
.error.intrusion {
  background-image: url("/image/hacked.png");
}
.seriousError {
  @extend .error;
  border-width: 3px;
}
```

生成的 CSS：

```css
.error, .seriousError {
  border: 1px #f00;
  background-color: #fdd; 
}

.error.intrusion, .seriousError.intrusion {
  background-image: url("/image/hacked.png"); 
}

.seriousError {
  border-width: 3px; 
}
```

实际上，Sass 是这样完成继承的：所有出现继承选择器的地方（比如此处的 `.error`），都会添加引用该继承的选择器（比如此处的 `.seriousError`）。

下面来看一个多继承的示例：

```scss
.error {
  border: 1px #f00;
  background-color: #fdd;
}
.attention {
  font-size: 3em;
  background-color: #ff0;
}
.seriousError {
  @extend .error;
  @extend .attention;
  border-width: 3px;
}
```

生成的 CSS：

```
.error, .seriousError {
  border: 1px #f00;
  background-color: #fdd; 
}

.attention, .seriousError {
  font-size: 3em;
  background-color: #ff0; 
}

.seriousError {
  border-width: 3px; 
}
```

由于继承没有层级的限制，所以很容易会形成链式继承，不过其继承规则不变：

```scss
.error {
  border: 1px #f00;
  background-color: #fdd;
}
.seriousError {
  @extend .error;
  border-width: 3px;
}
.criticalError {
  @extend .seriousError;
  position: fixed;
  top: 10%;
  bottom: 10%;
  left: 10%;
  right: 10%;
}
```

生成的 CSS：

```css
.error, .seriousError, .criticalError {
  border: 1px #f00;
  background-color: #fdd; 
}

.seriousError, .criticalError {
  border-width: 3px; 
}

.criticalError {
  position: fixed;
  top: 10%;
  bottom: 10%;
  left: 10%;
  right: 10%; 
}
```

使用 `%` 标识符创建的规则集，不会被解析到最终的 CSS 文件中。

```scss
// This ruleset won't be rendered on its own.
#context a%extreme {
  color: blue;
  font-weight: bold;
  font-size: 2em;
}

.notice {
  @extend %extreme;
}
```

生成的 CSS：

```css
#context a.notice {
  color: blue;
  font-weight: bold;
  font-size: 2em; 
}
```

有时候因为某些原因，继承的规则集可能不存在，为了避免编译中报错，可以添加 `!optional` 标识符：

```scss
a.important {
  @extend .notice !optional;
}
```

由于没有定义 `.notice` 规则集，所以这里的输出为空。

目前在其他指令，比如 `@media` 中使用 `@extend` 还会报错，未来可能会完善相关机制，在此之前，应该避免将 `@extend` 指令嵌套到其他指令中。

### `@at-root`

`@at-root` 指令用于将嵌套内的规则集提取到外部：

```scss
.parent {
  ...
  @at-root {
    .child1 { ... }
    .child2 { ... }
  }
  .step-child { ... }
}
```

生成的 CSS：

```
.parent { ... }
.child1 { ... }
.child2 { ... }
.parent .step-child { ... }
```

此外，还有 `@at-root (without: ...)` 和 `@at-root (with: ...)` 用法，主要用于移除或者添加其他指令，下面是一个移除的示例：

```scss
@media print {
  .page {
    width: 8in;
    @at-root (without: media) {
      color: red;
    }
  }
}
```

生成的 CSS：

```
@media print {
  .page {
    width: 8in;
  }
}
.page {
  color: red;
}
```

### `@debug`

`@debug` 指令用于调试 SassScript 的表达式：

```scss
@debug 10em + 12em;
```

输出结果：

```
Line 1 DEBUG: 22em
```

### `@warn`

`@warn` 指令，顾名思义，就是提醒，这种提醒可能用于纠正未知的错误，可能用于纠正不规范的错误：

```scss
@mixin adjust-location($x, $y) {
  @if unitless($x) {
    @warn "Assuming #{$x} to be in pixels";
    $x: 1px * $x;
  }
  @if unitless($y) {
    @warn "Assuming #{$y} to be in pixels";
    $y: 1px * $y;
  }
  position: relative; left: $x; top: $y;
}
```

### `@error`

`@error` 指令和 `@warn` 指令非常类似，唯一的区别在于，当触发 `@error` 时，会阻塞编译过程：

```scss
@mixin adjust-location($x, $y) {
  @if unitless($x) {
    @error "$x may not be unitless, was #{$x}.";
  }
  @if unitless($y) {
    @error "$y may not be unitless, was #{$y}.";
  }
  position: relative; left: $x; top: $y;
}
```

### `@if`

`@if` 指令用于构成条件判断，如果判断结果不是 `false` 或者 `null`，就执行条件内的逻辑操作：

```scss
p {
  @if 1 + 1 == 2 { border: 1px solid;  }
  @if 5 < 3      { border: 2px dotted; }
  @if null       { border: 3px double; }
}
```

生成的 CSS：

```
p {
  border: 1px solid; 
}
```

对于复杂的条件判断，可以使用 `@if ... @else if ... @else` 指令：

```scss
$type: monster;
p {
  @if $type == ocean {
    color: blue;
  } @else if $type == matador {
    color: red;
  } @else if $type == monster {
    color: green;
  } @else {
    color: black;
  }
}
```

生成的 CSS：

```css
p {
  color: green; 
}
```

### `@for`

`@for ... from ... through ...` 用来执行循环语句：

```scss
@for $i from 1 through 3 {
  .item-#{$i} { width: 2em * $i; }
}
```

生成的 CSS：

```css
.item-1 {
  width: 2em; 
}
.item-2 {
  width: 4em; 
}
.item-3 {
  width: 6em; 
}
```

### `@each`

`@each` 指令主要用来遍历列表或者 map：

```scss
@each $animal in (puma sea-slug egret salamander) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
  }
}
```

生成的 CSS：

```css
.puma-icon {
  background-image: url('/images/puma.png'); 
}
.sea-slug-icon {
  background-image: url('/images/sea-slug.png'); 
}
.egret-icon {
  background-image: url('/images/egret.png'); 
}
.salamander-icon {
  background-image: url('/images/salamander.png'); 
}
```

多维列表的遍历：

```scss
@each $animal, $color, $cursor in (puma, black, default),
                                  (sea-slug, blue, pointer),
                                  (egret, white, move) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
    border: 2px solid $color;
    cursor: $cursor;
  }
}
```

生成的 CSS：

```css
.puma-icon {
  background-image: url('/images/puma.png');
  border: 2px solid black;
  cursor: default; }
.sea-slug-icon {
  background-image: url('/images/sea-slug.png');
  border: 2px solid blue;
  cursor: pointer; }
.egret-icon {
  background-image: url('/images/egret.png');
  border: 2px solid white;
  cursor: move; }
```

遍历 map：

```scss
@each $header, $size in (h1: 2em, h2: 1.5em, h3: 1.2em) {
  #{$header} {
    font-size: $size;
  }
}
```

生成的 CSS：

```css
h1 {
  font-size: 2em; 
}
h2 {
  font-size: 1.5em; 
}
h3 {
  font-size: 1.2em; 
}
```

### `@while`

`@while` 指令是另一种形式的循环：

```scss
$i: 6;
@while $i > 0 {
  .item-#{$i} { width: 2em * $i; }
  $i: $i - 2;
}
```

生成的 CSS：

```css
.item-6 {
  width: 12em; 
}
.item-4 {
  width: 8em; 
}
.item-2 {
  width: 4em; 
}
```

## 混合宏

混合宏是 Sass 中代码片段得以复用的强大基础：

```scss
// 定义一个混合宏
@mixin clearfix {
  display: inline-block;
  &:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden;
  }
  * html & { height: 1px }
}

// 调用一个混合宏
.float {
  @include clearfix;
}
```

生成的 CSS：

```css
.float {
  display: inline-block;
}
.float:after {
  content: ".";
  display: block;
  height: 0;
  clear: both;
  visibility: hidden;
}
* html .float {
  height: 1px;
}
```

混合宏之中可以包含其他的混合宏：

```scss
@mixin compound {
  @include highlighted-background;
  @include header-text;
}
```

### 混合宏下的参数

Sass 下的混合宏可以使用多种参数：默认值参数、关键字参数、不定量参数……

普通参数：

```scss
@mixin sexy-border($color, $width) {
  border: {
    color: $color;
    width: $width;
    style: dashed;
  }
}
p { @include sexy-border(blue, 1in); }
```

生成的 CSS：

```css
p {
  border-color: blue;
  border-width: 1in;
  border-style: dashed; 
}
```

默认参数：

```scss
@mixin sexy-border($color, $width: 1in) {
  border: {
    color: $color;
    width: $width;
    style: dashed;
  }
}
p { @include sexy-border(blue); }
h1 { @include sexy-border(blue, 2in); }
```

生成的 CSS：

```css
p {
  border-color: blue;
  border-width: 1in;
  border-style: dashed; 
}

h1 {
  border-color: blue;
  border-width: 2in;
  border-style: dashed; 
}
```

关键字参数：

```scss
@mixin sexy-border($color: red, $width: 1in) {
  border: {
    color: $color;
    width: $width;
    style: dashed;
  }
}
p { @include sexy-border($width: 2in); }
```

生成的 CSS：

```css
p {
  border-color: red;
  border-width: 2in;
  border-style: dashed;
}
```

不定量参数：

```scss
@mixin box-shadow($shadows...) {
  -moz-box-shadow: $shadows;
  -webkit-box-shadow: $shadows;
  box-shadow: $shadows;
}

.shadows {
  @include box-shadow(0px 4px 5px #666, 2px 6px 10px #999);
}
```

生成的 CSS：

```css
.shadows {
  -moz-box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
  -webkit-box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
  box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
}
```

另一种不定量参数的写法：

```scss
@mixin colors($text, $background, $border) {
  color: $text;
  background-color: $background;
  border-color: $border;
}

$values: #ff0000, #00ff00, #0000ff;
.primary {
  @include colors($values...);
}

$value-map: (text: #00ff00, background: #0000ff, border: #ff0000);
.secondary {
  @include colors($value-map...);
}
```

生成的 CSS：

```css
.primary {
  color: #ff0000;
  background-color: #00ff00;
  border-color: #0000ff;
}

.secondary {
  color: #00ff00;
  background-color: #0000ff;
  border-color: #ff0000;
}
```

### 混合宏中的 `@content`

`@content` 在混合宏中算是一种插值指令，类似占位符。当调用这段混合宏并附加规则时，附加的规则就会替代该指令输出到 CSS 中：

```scss
@mixin apply-to-ie6-only {
  * html {
    @content;
  }
}
@include apply-to-ie6-only {
  #logo {
    background-image: url(/logo.gif);
  }
}
```

生成的 CSS：

```css
* html #logo {
  background-image: url(/logo.gif);
}
```

## 函数指令

Sass 提供了 `@function` 和 `@return` 两个指令用来创建函数和返回函数值。在函数中，同样适用多种参数类型：

```scss
$grid-width: 40px;
$gutter-width: 10px;

@function grid-width($n) {
  @return $n * $grid-width + ($n - 1) * $gutter-width;
}

#sidebar { width: grid-width(5); }
```

生成的 CSS：

```css
#sidebar {
  width: 240px; 
}
``` 

###### 参考资料

- [Sass 官方文档-基础语法部分](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps)
- [Sass 官方文档-内建函数部分](http://sass-lang.com/documentation/Sass/Script/Functions.html)
